### ISSUE TITLE
Pre-announcement checklist

### ISSUE THREAD

**Issue by omasanori** [omasanori/rugs#7]
Rugs is a *secret* project now; we need preparation before sending an announcement to the Haskell community.

- [ ] README
- [ ] Description
- [ ] Contributing Guidelines
- [ ] Template for issues and pull requests
- [ ] Code of Conduct? ([Contributor Covenant](https://www.contributor-covenant.org/) and [Community Covenant](https://community-covenant.net/) maybe?)
  - [ ] Contact?
  - [ ] Enforcement Guidelines?
- [ ] Continuous integration (GitHub Actions, Travis CI, others?)
- [ ] Documentation hosting (Read the Docs?)
- [ ] Communication channel (Matrix, Zulip, Gitter or something)
